test:test-subseq.o maxSeq.o
	gcc test-subseq.o maxSeq.o -o test
test-subseq.o: test-subseq.c
	gcc -c -pedantic -std=gnu99 -Wall -Werror test-subseq.c
maxSeq.o: maxSeq.c
	gcc -c -pedantic -std=gnu99 -Wall -Werror maxSeq.c
